## Megalist: https://gist.github.com/itoonx/2021be2dab6e5c2fa7931deb70377697
## Max number of tokens to use for repo map, use 0 to disable (default: 1024)
## This controls the size of the repository map for context when using the AI assistant.
map-tokens: 2048

## Specify the model to use for chat and code assistance
## Available models: gpt-4o, claude-3-5-sonnet, o1-preview, deepseek, etc.
model: gpt-4o

## Enable dark mode for a better terminal appearance on dark backgrounds
dark-mode: true

## Enable pretty, colorized output (default: true)
pretty: true

## Disable streaming responses; waits for full response before displaying
stream: false

## Disable showing differences between current and previous file versions
show-diffs: false

## Disable automatic commits after changes made by the AI
auto-commits: false

## Prevent the AI from suggesting shell commands during chats
no-suggest-shell-commands: true

## Load environment variables from a specified file (default: .env in git root)
env-file: .env.aider

## Number of pings to keep the prompt cache alive at 5-minute intervals (default: 0)
cache-keepalive-pings: 5

## Specify which files are included in the session
file: ["*.ps1"]

## Enable caching of prompts to reduce token costs (default: false)
cache-prompts: true

## Disable streaming of token-based calculations for caching
no-stream: true

## Add aider-specific files to .gitignore (default: true)
## Set to false as its already tehre
gitignore: false

## Automatically lints code after changes using PSScriptAnalyzer (PowerShell linting)
auto-lint: true

## Command to lint PowerShell code using PSScriptAnalyzer
lint-cmd: "pwsh -Command Invoke-ScriptAnalyzer -Path *.ps1"

## Automatically runs tests after code changes using Pester
auto-test: true

## Command to run PowerShell tests using Pester
test-cmd: "pwsh -Command Invoke-Pester -Path .\\Tests"

# History Files
input-history-file: .aider/aider.input.history
chat-history-file: .aider/aider.chat.history.md
llm-history-file: .aider/aider.llm.history

# Model Settings
model-settings-file: .aider/.aider.model.settings.yml
model-metadata-file: .aider/.aider.model.metadata.json

# Ignore file (for Git)
aiderignore: .aider/.aiderignore

# Environment File
env-file: .aider/.env

# model: deepseek/deepseek-chat
# model: claude-3-5-sonnet-20240620
# model: openrouter/openai/o1-preview
