services:
  mssql:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-fake12345FAKE67890APIKEY12345}
      - ACCEPT_EULA=${ACCEPT_EULA:-Y}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD:-dbatools.IO}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1433:1433
    volumes:
      - ../..:/workspaces
    command: ["/opt/mssql/bin/sqlservr"]