version: '3.7'
services:
  mssql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
    command: ["/opt/mssql/bin/sqlservr"]